### ISSUE TITLE
Ability to force Etcd API version

### ISSUE THREAD

**Issue by benbooth493** [mhausenblas/reshifter#4] opened 2017-07-18 09:59 UTC
Currently the code discovers the version of Etcd API.
I am running Etcd 3.1.6 but I use API V2. This means that I am currently unable to backup my cluster as it is detected as API V3.

I get the following message:

etcd: v3.1.2, secure etcd, SSL/TLS configure
distribution: Vanilla Kubernetes
Stats for known keys as per Kubernetes distribution:
number of keys: 0
total number of bytes to back up: 0

It would be great if it was possible to set RS_ETCD_API_VERSION env var to override auto-discovery.

I'm running reshifter-0.3.12

**Comment by mhausenblas** [comment] 2017-07-18 10:26
Thanks for raising this issue @benbooth493 and for giving ReShifter a try!

Now, I'm more than happy to provide a way to override auto-discovery (since it's really only a convenience functionality) but I'm somewhat surprised about the statement. Since you mentioned that you're using v0.3.12, I was under the impression I fixed the issue (v2 API in a V3 etcd) with this release. Can I ask you to do an `etcdctl ls` and `etcdctl get` (with `ETCDCTL_API=3` set) and share the output here pls? See also discussion in related #2 …

**Comment by benbooth493** [comment] 2017-07-18 11:05
This produces no output:
ETCDCTL_API=3 ./etcdctl --cacert /etc/etcd2/ssl/ca.pem --cert /etc/etcd2/ssl/etcd.pem --key /etc/etcd2/ssl/etcd-key.pem --endpoints https://ip-10-252-18-122.eu-west-1.compute.internal:2379 get / --prefix --keys-only

But this does:
ETCDCTL_API=2 ./etcdctl --ca-file /etc/etcd2/ssl/ca.pem --cert-file /etc/etcd2/ssl/etcd.pem --key-file /etc/etcd2/ssl/etcd-key.pem --endpoints https://x.x.x.x:2379 ls
/coreos.com
/registry

**Comment by mhausenblas** [comment] 2017-07-18 12:18
OK, thanks @benbooth493. I thought I've covered it in the test cases but apparently not. Will reproduce and debug. Please hold the line :)

**Comment by mhausenblas** [comment] 2017-07-18 15:26
Turns out it was a combination of logical bug and simple stupidity on my end. Passing the relevant test cases now and the [v0.3.13](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.13-alpha) release *should* address it. I sincerely hope so! 

@benbooth493 can you please give it a try?

**Comment by benbooth493** [comment] 2017-07-18 15:29
It's not looking good I'm afraid:
```
Result
There was a problem collecting endpoint stats:
undefined
```

There's nothing in the logs at DEBUG level either.

**Comment by mhausenblas** [comment] 2017-07-18 15:35
Hmmm, interesting. But not too bad. I've got an idea, lemme try something and come back real soon …

**Comment by mhausenblas** [comment] 2017-07-18 15:45
OK, so I tried to reproduce your issue and for me this works:

```
$ docker run --rm -p 8080:8080 quay.io/mhausenblas/reshifter:0.3.13
```
Then, I launch an etcd3 in v2 mode and add these two keys:

```
$ http http://localhost:2379/v2/keys/registry/namespaces                                                                 [0/146]
HTTP/1.1 200 OK
Content-Length: 287
Content-Type: application/json
Date: Tue, 18 Jul 2017 15:41:18 GMT
X-Etcd-Cluster-Id: b55d10073feab447
X-Etcd-Index: 5
X-Raft-Index: 6
X-Raft-Term: 2

{
    "action": "get",
    "node": {
        "createdIndex": 4,
        "dir": true,
        "key": "/registry/namespaces",
        "modifiedIndex": 4,
        "nodes": [
            {
                "createdIndex": 4,
                "key": "/registry/namespaces/kube-system",
                "modifiedIndex": 4,
                "value": "."
            },
            {
                "createdIndex": 5,
                "key": "/registry/namespaces/default",
                "modifiedIndex": 5,
                "value": "."
            }
        ]
    }
}
```

When I then do a backup via the app/UI, I indeed can create the backup and when I verify the backup it has these two keys in it. Any idea where we two differ now?

**Comment by mhausenblas** [comment] 2017-07-18 16:12
Just to be clear, I can confirm the stats issue, but the backup works for me (see above). Can you confirm that you can't produce a backup or is it 'just' the discovery/stats part, @benbooth493?

**Comment by benbooth493** [comment] 2017-07-19 08:34
Ok so the backup works fine. 👍

**Comment by mhausenblas** [comment] 2017-07-19 11:05
Awesome, thanks a lot for this confirmation @benbooth493 and working on the stats part as we speak, will keep you posted. BTW, would you still consider the original feature (overwrite auto-discovery) as valuable now, or …?

**Comment by mhausenblas** [comment] 2017-07-19 12:49
@benbooth493 just released [v0.3.14](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.14-alpha) … can you maybe give it a spin and lemme know how it rolls?

**Comment by mhausenblas** [comment] 2017-07-20 12:50
@benbooth493 please use the newest release [v0.3.15-alpha](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.15-alpha) when you give it a try, yes?

**Comment by mhausenblas** [comment] 2017-07-21 06:17
Well, independent of you outcome @benbooth493 I'll need to implement the 'overwrite auto-discovery' feature anyways since @eremid ran into the issue of ReShifter restoring a previous v2 API into a v3 API which is obviously not cool. So, @eremid no need to create a new issue, I'll use this one here to work against and would ask you to comment here please.

**Comment by mhausenblas** [comment] 2017-07-21 09:43
@benbooth493 I've now implemented the desired feature in [v0.3.17-alpha](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.17-alpha) … would you have time to give it a try? NOTE: CLI tool, `rcli`-only feature for now, need to update the app.

**Comment by mhausenblas** [comment] 2017-07-21 15:25
Now, with [v0.3.19](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.19-alpha), also available in the app (Web UI). FYI @eremid and @benbooth493 …

**Comment by mhausenblas** [comment] 2017-07-24 08:25
@benbooth493 I think I'll close this for now, since the feature is available both in `rcli` and the app, but happy to re-open if necessary …

**Closed by mhausenblas** 2017-07-24 08:25 UTC
Labels: app/UI, CLI, enhancement, lib
