### ISSUE TITLE
Cannot build from source: undefined: tls.CertificateRequestInfo

### ISSUE THREAD

**Issue by dohnto** [mhausenblas/reshifter#5] opened 2017-07-19 06:42 UTC
In order to debug #2 I tried to build *reshifter* from source, following `dev.md` document.

You can reproduce my build by running:

```bash
# in reshifter directory
$ git rev-parse HEAD
3088d324f4e2bd545662673999160bd8aab56604
$ docker run -it -v $PWD:/go/src/github.com/mhausenblas/reshifter debian:stretch
$  docker run -it -v $PWD:/go/src/github.com/mhausenblas/reshifter -w /go/src/github.com/mhausenblas/reshifter -e GOPATH=/go debian:stretch
# inside docker cointainer
$ apt-get update
$ apt-get install -y golang git make
$ go get -u github.com/golang/dep/cmd/dep
$ /go/bin/dep ensure
$ make gbuild
GOOS=linux GOARCH=amd64 go build -ldflags "-X main.releaseVersion=0.3.13" .
# mhausenblas/reshifter/vendor/github.com/coreos/etcd/pkg/transport
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: cfg.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: undefined: tls.CertificateRequestInfo
vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:151: undefined: net.DefaultResolver in net.DefaultResolver.LookupHost
Makefile:15: recipe for target 'gbuild' failed
make: *** [gbuild] Error 2
```

**EDIT:** updated the code to improve compaction
**NOTE:** I haven't developed in golang lately so maybe missing something obvious... but maybe it can be included in `dev.md`

Thanks!

**Comment by mhausenblas** [comment] 2017-07-19 07:16
@dohnto oh wow, thanks a lot for doing this, I so much appreciate it!! Will try to figure out what the problem is here ASAP (note: I'm developing on macOS, never tried what you did above).

**Comment by mhausenblas** [comment] 2017-07-19 13:22
As the awesome @carolynvs from the `dep` team rightly pointed out (thanks, again!!) the root problem here is that the Go version in the Docker image is out of date (v1.7, where I'm using v1.8). This should fix this issue, can you try and confirm please, @dohnto?

**Comment by mhausenblas** [comment] 2017-07-20 12:49
Can I close this one @dohnto?

**Comment by mhausenblas** [comment] 2017-07-24 08:24
OK, @dohnto I think I'm gonna close this one for now, if the issue persists, happy to re-open it.

**Closed by mhausenblas** 2017-07-24 08:24 UTC
Labels: bug, build-related

**Comment by dohnto** [comment] 2017-07-24 16:43
Yes, golang 1.8  fixed this one for me.
